"""empty message

Revision ID: 65e67a652f38
Revises: 087b9165b46a
Create Date: 2019-04-22 19:53:03.152832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e67a652f38'
down_revision = '087b9165b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('previous_expungements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'previous_expungements')
    # ### end Alembic commands ###
