"""remove unique contraint on qualifying question

Revision ID: 73fa18b37f37
Revises: 686427549b61
Create Date: 2019-03-18 19:00:09.222286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fa18b37f37'
down_revision = '686427549b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qualifying__answer_user_session', table_name='qualifying__answer')
    op.create_index(op.f('ix_qualifying__answer_user_session'), 'qualifying__answer', ['user_session'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifying__answer_user_session'), table_name='qualifying__answer')
    op.create_index('ix_qualifying__answer_user_session', 'qualifying__answer', ['user_session'], unique=1)
    # ### end Alembic commands ###
