"""qualifying question and answer tables

Revision ID: 9f02092798e8
Revises: 
Create Date: 2019-03-10 19:07:04.188694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f02092798e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifying__answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_session', sa.String(length=250), nullable=True),
    sa.Column('question_id', sa.String(length=250), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('qualifying_answer', sa.String(length=250), nullable=True),
    sa.Column('question_version_number', sa.Float(asdecimal=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifying__answers_timestamp'), 'qualifying__answers', ['timestamp'], unique=False)
    op.create_index(op.f('ix_qualifying__answers_user_session'), 'qualifying__answers', ['user_session'], unique=True)
    op.create_table('qualifying__questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('disqualifying_answer', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualifying__questions')
    op.drop_index(op.f('ix_qualifying__answers_user_session'), table_name='qualifying__answers')
    op.drop_index(op.f('ix_qualifying__answers_timestamp'), table_name='qualifying__answers')
    op.drop_table('qualifying__answers')
    # ### end Alembic commands ###
