"""add lingering fields

Revision ID: bec81ee56596
Revises: 65e67a652f38
Create Date: 2019-04-24 16:48:48.939252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec81ee56596'
down_revision = '65e67a652f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('full_license_issuing_state', sa.String(length=64), nullable=True))
    op.add_column('conviction', sa.Column('approximate_date_of_charge', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conviction', 'approximate_date_of_charge')
    op.drop_column('client', 'full_license_issuing_state')
    # ### end Alembic commands ###
