"""empty message

Revision ID: c080491115a4
Revises: 123bd12b374c
Create Date: 2019-04-16 13:36:08.313398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c080491115a4'
down_revision = '123bd12b374c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('conviction_charge_type', sa.String(), nullable=True))
    op.add_column('charge', sa.Column('conviction_class_type', sa.String(), nullable=True))
    op.drop_column('charge', 'class_type')
    op.drop_column('charge', 'charge_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('charge_type', sa.VARCHAR(length=11), nullable=True))
    op.add_column('charge', sa.Column('class_type', sa.VARCHAR(length=9), nullable=True))
    op.drop_column('charge', 'conviction_class_type')
    op.drop_column('charge', 'conviction_charge_type')
    # ### end Alembic commands ###
