"""empty message

Revision ID: c818186c9740
Revises: 205176618653
Create Date: 2019-04-20 15:21:47.116412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c818186c9740'
down_revision = '205176618653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('cms_case_number', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'cms_case_number')
    # ### end Alembic commands ###
