"""client, conviction, charges

Revision ID: d4d79c5644df
Revises: 73fa18b37f37
Create Date: 2019-03-21 14:27:49.779163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d79c5644df'
down_revision = '73fa18b37f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.String(), nullable=True),
    sa.Column('sentence', sa.String(), nullable=True),
    sa.Column('charge_type', sa.Enum('FELONY', 'MISDEMEANOR', name='charge'), nullable=True),
    sa.Column('class_type', sa.Enum('A', 'B', 'C', 'D', 'E', 'UNDEFINED', name='class'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conviction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('record_name', sa.String(), nullable=True),
    sa.Column('release_status', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conviction')
    op.drop_table('client')
    op.drop_table('charge')
    # ### end Alembic commands ###
