"""conviction-charge-client-models

Revision ID: ff4bd320cd32
Revises: 73fa18b37f37
Create Date: 2019-04-03 16:03:22.059722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4bd320cd32'
down_revision = '73fa18b37f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conviction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('record_name', sa.String(), nullable=True),
    sa.Column('release_status', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('expungeable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.String(), nullable=True),
    sa.Column('sentence', sa.String(), nullable=True),
    sa.Column('expungeable', sa.Boolean(), nullable=True),
    sa.Column('charge_type', sa.Enum('FELONY', 'MISDEMEANOR', name='charge'), nullable=True),
    sa.Column('class_type', sa.Enum('A', 'B', 'C', 'D', 'E', 'UNDEFINED', name='class'), nullable=True),
    sa.Column('conviction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conviction_id'], ['conviction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge')
    op.drop_table('conviction')
    op.drop_table('client')
    # ### end Alembic commands ###
